name: gamepads_workspace
repository: https://github.com/flame-engine/gamepads
workspace:
    - packages/gamepads
    - packages/gamepads/example
    - packages/gamepads_android
    - packages/gamepads_darwin
    - packages/gamepads_ios
    - packages/gamepads_linux
    - packages/gamepads_platform_interface
    - packages/gamepads_windows

environment:
  sdk: '>=3.9.0 <4.0.0'

dev_dependencies:
  melos: ^7.1.0

melos:
  command:
    version:
      branch: main

    bootstrap:
      environment:
        sdk: ">=3.9.0 <4.0.0"
        flutter: ">=3.35.0"
      dev_dependencies:
        flame_lint: ^1.4.1

  scripts:
    lint:
      run: melos run analyze && melos run format
      description: Run all static analysis checks.

    analyze:
      run: melos exec -c 10 flutter analyze --fatal-infos
      description: Run `flutter analyze` for all packages.

    format:
      run: melos exec dart format . --fix
      description: Run `dart format` for all packages.

    format-check:
      run: melos exec dart format . --set-exit-if-changed
      description: Run `dart format` checks for all packages.

    dartdoc:
      run: melos exec flutter pub run dartdoc
      description: Run dartdoc checks for all non-example packages.
      packageFilters:
        ignore: "*_example"

    test:select:
      run: melos exec flutter test
      packageFilters:
        dirExists: test
      description: Run `flutter test` for selected packages.

    test:
      run: melos run test:select --no-select
      description: Run all Flutter tests in this project.

