name: gamepads_linux
resolution: workspace
description: Linux implementation of gamepads, a Flutter plugin to handle gamepad input across multiple platforms.
version: 0.1.1+3
homepage: https://github.com/flame-engine/gamepads
repository: https://github.com/flame-engine/gamepads/tree/main/packages/gamepads_linux

flutter:
  plugin:
    implements: gamepads
    platforms:
      linux:
        pluginClass: GamepadsLinuxPlugin

environment:
  sdk: ">=3.9.0 <4.0.0"
  flutter: ">=3.35.0"

dependencies:
  flutter:
    sdk: flutter
  gamepads_platform_interface: ^0.1.2+1

dev_dependencies:
  flame_lint: ^1.4.1
  flutter_test:
    sdk: flutter
