name: gamepads_android
resolution: workspace
description: Android implementation of gamepads, a Flutter plugin to handle gamepad input across multiple platforms.
version: 0.1.3
homepage: https://github.com/flame-engine/gamepads
repository: https://github.com/flame-engine/gamepads/tree/main/packages/gamepads_android

flutter:
  plugin:
    platforms:
      android:
        package: org.flame_engine.gamepads_android
        pluginClass: GamepadsAndroidPlugin

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter
  gamepads_platform_interface: ^0.1.2+1

dev_dependencies:
  flame_lint: ^1.4.0
  flutter_test:
    sdk: flutter
