name: gamepads_platform_interface
resolution: workspace
description: The platform interface for gamepads, a Flutter plugin to handle gamepad input across multiple platforms.
version: 0.1.2+1
homepage: https://github.com/flame-engine/gamepads
repository: https://github.com/flame-engine/gamepads/tree/main/packages/gamepads_platform_interface

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flame_lint: ^1.4.0
  flutter_test:
    sdk: flutter
