name: gamepads_darwin
resolution: workspace
description: MacOS implementation of gamepads, a Flutter plugin to handle gamepad input across multiple platforms.
version: 0.1.2+2
homepage: https://github.com/flame-engine/gamepads
repository: https://github.com/flame-engine/gamepads/tree/main/packages/gamepads_darwin

flutter:
  plugin:
    implements: gamepads
    platforms:
      macos:
        pluginClass: GamepadsDarwinPlugin

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter
  gamepads_platform_interface: ^0.1.2+1

dev_dependencies:
  flame_lint: ^1.4.0
  flutter_test:
    sdk: flutter
