/// Script to generate the embedded SDL GameController DB Dart file from
/// the raw gamecontrollerdb.txt.
///
/// Usage:
///   dart run tool/update_controller_database.dart
///
/// This filters the database to only Linux and Windows entries (the
/// platforms that need VID/PID-based mapping) and embeds them as a
/// const string in a generated Dart file.
library;

import 'dart:io';

void main() {
  final inputFile = File(
    'lib/src/mappings/data/gamecontrollerdb.txt',
  );
  final outputFile = File(
    'lib/src/mappings/data/gamecontrollerdb_data.dart',
  );

  if (!inputFile.existsSync()) {
    const url =
        'https://raw.githubusercontent.com/'
        'gabomdq/SDL_GameControllerDB/master/'
        'gamecontrollerdb.txt';
    stderr.writeln(
      'Error: gamecontrollerdb.txt not found. '
      'Download it first:\n'
      '  curl -sL $url -o ${inputFile.path}',
    );
    exit(1);
  }

  final lines = inputFile.readAsLinesSync();

  final filteredLines = <String>[];
  for (final line in lines) {
    final trimmed = line.trim();
    if (trimmed.isEmpty || trimmed.startsWith('#')) {
      continue;
    }
    if (trimmed.contains('platform:Linux') ||
        trimmed.contains('platform:Windows')) {
      filteredLines.add(trimmed);
    }
  }

  final escapedLines = filteredLines
      .map((line) => line.replaceAll("'", r"\'"))
      .join('\n');

  final output = StringBuffer()
    ..writeln('// GENERATED FILE — DO NOT EDIT')
    ..writeln('//')
    ..writeln(
      '// Source: https://github.com/gabomdq/SDL_GameControllerDB',
    )
    ..writeln(
      '// Generated by: dart run tool/update_controller_database.dart',
    )
    ..writeln(
      '// Entries: ${filteredLines.length} '
      '(Linux and Windows only)',
    )
    ..writeln()
    ..writeln(
      '/// Embedded SDL GameController DB entries for Linux and '
      'Windows.',
    )
    ..writeln("const gamecontrollerDbData = '''")
    ..writeln(escapedLines)
    ..writeln("''';");

  outputFile.writeAsStringSync(output.toString());

  stdout.writeln(
    'Generated ${outputFile.path} with '
    '${filteredLines.length} entries.',
  );
}
